// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorneoDeportivo.Infrastructure.Persistence;

#nullable disable

namespace TorneoDeportivo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TorneoDbContext))]
    [Migration("20260819013545_CompetidorSinCategoriaYConSexo")]
    partial class CompetidorSinCategoriaYConSexo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("RangoEdadMax")
                        .HasColumnType("integer")
                        .HasColumnName("rango_edad_max");

                    b.Property<int?>("RangoEdadMin")
                        .HasColumnType("integer")
                        .HasColumnName("rango_edad_min");

                    b.Property<string>("RangoGraduacionMax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rango_graduacion_max");

                    b.Property<string>("RangoGraduacionMin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rango_graduacion_min");

                    b.Property<decimal?>("RangoPesoMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rango_peso_max");

                    b.Property<decimal?>("RangoPesoMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rango_peso_min");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.Property<string>("TipoCompetencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_competencia");

                    b.Property<Guid>("TorneoId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneo_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("TorneoId")
                        .HasDatabaseName("ix_categorias_torneo_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Competidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Altura")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("altura");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("Escuela")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("escuela");

                    b.Property<string>("Graduacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("graduacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("peso");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsable");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<Guid>("TorneoId")
                        .HasColumnType("uuid")
                        .HasColumnName("torneo_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competidores");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_competidores_categoria_id");

                    b.HasIndex("TorneoId")
                        .HasDatabaseName("ix_competidores_torneo_id");

                    b.ToTable("competidores", (string)null);
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.LlaveCompetencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("Competidor1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("competidor1id");

                    b.Property<Guid?>("Competidor2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("competidor2id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<Guid?>("GanadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ganador_id");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.Property<int>("Ronda")
                        .HasColumnType("integer")
                        .HasColumnName("ronda");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_llaves_competencia");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_llaves_competencia_categoria_id");

                    b.HasIndex("Competidor1Id")
                        .HasDatabaseName("ix_llaves_competencia_competidor1id");

                    b.HasIndex("Competidor2Id")
                        .HasDatabaseName("ix_llaves_competencia_competidor2id");

                    b.HasIndex("GanadorId")
                        .HasDatabaseName("ix_llaves_competencia_ganador_id");

                    b.ToTable("llaves_competencia", (string)null);
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Torneo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("ImagenFlyer")
                        .HasColumnType("text")
                        .HasColumnName("imagen_flyer");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("lugar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_torneos");

                    b.ToTable("torneos", (string)null);
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("TorneoDeportivo.Domain.Entities.Torneo", "Torneo")
                        .WithMany("Categorias")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_torneos_torneo_id");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Competidor", b =>
                {
                    b.HasOne("TorneoDeportivo.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Competidores")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_competidores_categorias_categoria_id");

                    b.HasOne("TorneoDeportivo.Domain.Entities.Torneo", "Torneo")
                        .WithMany("Competidores")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competidores_torneos_torneo_id");

                    b.Navigation("Categoria");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.LlaveCompetencia", b =>
                {
                    b.HasOne("TorneoDeportivo.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Llaves")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_llaves_competencia_categorias_categoria_id");

                    b.HasOne("TorneoDeportivo.Domain.Entities.Competidor", "Competidor1")
                        .WithMany()
                        .HasForeignKey("Competidor1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_llaves_competencia_competidores_competidor1id");

                    b.HasOne("TorneoDeportivo.Domain.Entities.Competidor", "Competidor2")
                        .WithMany()
                        .HasForeignKey("Competidor2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_llaves_competencia_competidores_competidor2id");

                    b.HasOne("TorneoDeportivo.Domain.Entities.Competidor", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_llaves_competencia_competidores_ganador_id");

                    b.Navigation("Categoria");

                    b.Navigation("Competidor1");

                    b.Navigation("Competidor2");

                    b.Navigation("Ganador");
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Competidores");

                    b.Navigation("Llaves");
                });

            modelBuilder.Entity("TorneoDeportivo.Domain.Entities.Torneo", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Competidores");
                });
#pragma warning restore 612, 618
        }
    }
}
